README.md
docs/compile.md
docs/early-hints.md

Thanks for creating this project and for publishing it as open source!
This PR includes some typo fixes and doc tweaks for your consideration. Thanks.

[Docs] Minor typos and tweaks

---

docs/config.md

Missing backslash for line continuation

---

docs/worker.md

Thanks a lot for this awesome projet 😍 
A little PR linked to https://github.com/dunglas/frankenphp/issues/31

APP_RUNTIME as docker environment variable

---

Dockerfile
Dockerfile.dev
docs/compile.md
testdata/Caddyfile

It's now possible to use the official PHP 8.2 version.

feat: use mainline PHP 8.2

---

Dockerfile.alpine

Should fix the CI: https://github.com/dunglas/frankenphp/actions/runs/3297768140/jobs/5439005535

fix: Docker images

---

docs/docker.md
frankenphp.c

Closes https://github.com/dunglas/frankenphp/issues/41.

feat: remove automatic exceptions handling

---

frankenphp.c

fix: memory leak in worker mode

---

.gitignore
frankenphp.c

fix: remove some more memory leaks in worker mode 

---

README.md

docs: add Sulu tutorial

---

frankenphp.c
frankenphp.go
frankenphp.h
worker.go

Before:
```
goos: darwin
goarch: arm64
pkg: github.com/dunglas/frankenphp
BenchmarkHelloWorld
BenchmarkHelloWorld-8   	    3128	    380514 ns/op	   20509 B/op	      33 allocs/op
PASS
ok  	github.com/dunglas/frankenphp	2.284s
```
After:
```
goos: darwin
goarch: arm64
pkg: github.com/dunglas/frankenphp
BenchmarkHelloWorld
BenchmarkHelloWorld-8   	    3144	    362953 ns/op	   20517 B/op	      33 allocs/op
PASS
ok  	github.com/dunglas/frankenphp	2.163s
```

perf: remove an extra call to cgo

---

Dockerfile
Dockerfile.alpine

Update base image to RC7

---

Dockerfile
Dockerfile.alpine

[PHP 8.2](https://www.php.net/archive/2022.php#2022-12-08-1) has been released yesterday! Let's use it.

feat(docker): use the stable version of PHP 8.2

---

frankenphp.go

This prevents a compilation warning and a potential crash.

fix: set the _GNU_SOURCE macro to allow memrchr usage

---

docs/compile.md

Add the documentation for the install of pkg-config

fix: add the documentation for pkg-config install

---

.github/workflows/tests.yml
frankenphp.c

Support for the upcoming 8.3 version of PHP!

feat: compatibility with PHP 8.3

---

.github/workflows/tests.yml
Dockerfile.dev
frankenphp_test.go
testdata/connectionStatusLog.php
testdata/die.php
testdata/flush.php

Fixes #109.
@withinboredom could you take a look please?

test: fix and refactor some flaky tests

---

frankenphp.go
frankenphp_test.go
worker.go

fix: race condition on shutdown

---

frankenphp.go

fix: flush support with Caddy 2.7

---

frankenphp_test.go
testdata/large-request.php

test: add a test for large requests

---

.github/workflows/docker.yml
.github/workflows/tests.yml
Dockerfile
alpine.Dockerfile

See https://github.com/dunglas/frankenphp/pull/171#issuecomment-1678475911.

ci: set GODEBUG=cgocheck=2

---

.circleci/config.yml
.github/workflows/static.yml
.github/workflows/tests.yml
Dockerfile
alpine.Dockerfile
static-builder.Dockerfile

Build a static binary for macOS and Apple Silicon.
Also, add the PHP version to the version command.

feat: Apple Silicon static build and better version name

---

.github/workflows/docker.yml
Dockerfile
alpine.Dockerfile
caddy/frankenphp/Caddyfile
docker-bake.hcl

Add healthchecks and refactor images.
Close #204.

feat: improve Docker images

---

dev-alpine.Dockerfile

See https://github.com/php/php-src/issues/12234

upgrade go version + add alpine dockerfile

---

docs/config.md

Hi, this PR will fix docs: 
- path to Caddyfile
- short tips about php.ini in docker image

docs: explain php.ini configuration in docker

---

docs/config.md

add documentation for multiple workers (might change if we get named workers)

---

.github/workflows/docker.yml
.github/workflows/static.yml
.github/workflows/tests.yml

Import interesting changes from https://github.com/dunglas/frankenphp/pull/242.

test: refactor YAML files

---

caddy/frankenphp/main.go

See https://github.com/uber-go/automaxprocs/issues/18
Fixes #251

fix: disable automaxprocs logging

---

caddy/frankenphp/main.go

Follows #255.
Log the change of maxprocs, but using Zap.
cc @ruudk

chore: log maxprocs

---

docs/known-issues.md

Performance tip for get_browser, see #270

docs: get_browser performance

---

docs/static.md

doc: Update static-php urls

---

caddy/frankenphp/Caddyfile
docs/compile.md
docs/docker.md
docs/laravel.md
docs/worker.md

Closes https://github.com/dunglas/frankenphp/issues/280.

docs: improve workers docs

---

frankenphp.c

This patch adds support for [input filters](https://github.com/php/php-src/blob/master/docs/input-filter.md).
It also reduces the number of switches between C and Go.

feat: add support for input filters

---

docs/compile.md
frankenphp.c
frankenphp.go
testdata/Caddyfile
worker.go

Close #310.
This patch also contains some other minor fixes and improvements.

feat: detect when worker crashes or terminate normally

---

docs/worker.md

docs: don't stop the worker script even if a connection with a client is aborted

---

.dockerignore
Dockerfile
alpine.Dockerfile
build-static.sh
embed.go
static-builder.Dockerfile

This allows the preserve of permissions and modification dates.

feat: use tar to embed apps

---

docs/laravel.md

Just a suggestion for the config as I found myself unable to access files symlinked to the public folder which is a standard thing you might find in a Laravel application.

Update example Laravel config in the docs

---

.github/workflows/docker.yaml
.github/workflows/static.yaml

For https://github.com/dunglas/frankenphp/discussions/359.

ci: rebuild Docker images every night if necessary

---

build-static.sh
docs/embed.md

Fix the slight issues found during @weaverryan live.

ci: add missing Go package on Mac

---

caddy/frankenphp/main.go

Backport of https://github.com/caddyserver/caddy/pull/5711#issuecomment-1855626821.

chore: improve automaxprocs logs

---

build-static.sh

Continuation of https://github.com/dunglas/frankenphp/pull/397.
cc @goossda.

feat: include debug symbols in CGO code

---

build-static.sh

Closes https://github.com/dunglas/frankenphp/issues/388.

fix: add back skipped extensions on Mac

---

testdata/benchmark.Caddyfile
testdata/load-test.js

Add a benchmark using K6.
To run it:
```
cd testdata
./frankenphp start --config benchmark.Caddyfile --adapter caddyfile
k6 run load-test.js
```
To investigate https://github.com/dunglas/frankenphp/issues/366.
For https://github.com/dunglas/frankenphp/issues/382.

perf: add benchmark

---

C-Thread-Pool/README.md
C-Thread-Pool/thpool.c
build-static.sh
frankenphp.go

Also, disable the debug mode of `static-php-cli`.

chore: switch to upstream C-Thread-Pool

---

build-static.sh

Close https://github.com/laravel/octane/issues/789.
Unlocked by https://github.com/crazywhalecc/static-php-cli/issues/293.

ci: add igbinary extension and LZ4 support to static builds

---

.github/workflows/static.yaml
docker-bake.hcl

Closes https://github.com/dunglas/frankenphp/issues/418.

ci: build Linux aarch64 binaries

---

frankenphp.c
frankenphp.go

This just brings over the optimization from #449, either one can be merged, but only one.

chore: optimization

---

docs/config.md

Add docs about including php ini files.

docs: php configuration guide

---

.github/workflows/docker.yaml
.github/workflows/static.yaml

Closes https://github.com/dunglas/frankenphp/issues/491.

ci: push dev Docker images to a dedicated repository

---

.github/workflows/docker.yaml
.github/workflows/static.yaml
docs/docker.md

docs: Docker image updates and tags

---

.github/workflows/docker.yaml

As requested on https://github.com/docker/buildx/issues/2229#issuecomment-1919260599.

ci: debug Docker buildx crash

---

frankenphp_test.go

Results on my Macbook Pro (MA Pro):
```
goos: darwin
goarch: arm64
pkg: github.com/dunglas/frankenphp
BenchmarkServerSuperGlobal
BenchmarkServerSuperGlobal-10    	    5636	    199244 ns/op	   14864 B/op	      94 allocs/op
PASS
ok  	github.com/dunglas/frankenphp	3.061s
```

perf: add $_SERVER creation benchmark

---

docs/config.md
frankenphp.c

Closes #541.
Closes #308.
Closes #314.

feat: automatically import environment variables in $_SERVER

---

docs/docker.md

The original example doesn't really build. Updated to include a working example.

Fix docs for running docker in non root mode

---

.github/workflows/static.yaml
.github/workflows/tests.yaml
caddy/go.mod
dev-alpine.Dockerfile
dev.Dockerfile
docker-bake.hcl
go.mod

feat: compile with Go 1.22

---

.github/workflows/static.yaml

Fix issues I introduced in #635.

ci: fix upload debug builds

---

frankenphp.c

See https://github.com/php/php-src/pull/10867.

perf: hint the number of threads to TSRM

---

build-static.sh

This will make issues like #709 and #710 easier to fix.

chore: enable the verbose mode of Static PHP CLI

---

build-static.sh
docs/fr/static.md
docs/static.md

Allow to disable UPX usage.
Closes #716.

feat: add an option to not compress the static binary

---

docs/cn/CONTRIBUTING.md

The file CONTRIBUTING.md was missing in the Chinese documentation.

docs: add the contributing.md file in Chinese

---

dev.Dockerfile
docs/cn/worker.md
docs/fr/worker.md
docs/tr/worker.md
docs/worker.md
frankenphp.c
frankenphp.go
testdata/worker-getopt.php
worker_test.go

Closes #767.
Partial fix for #592 (memory leak when dealing with cookies in worker mode).

fix: superglobals-realated crash with custom extensions in worker mode

---

docs/worker.md

update usage without symfony documentation

---

frankenphp.c
frankenphp_test.go
testdata/file-upload.php

Closes https://github.com/dunglas/frankenphp/issues/803.

fix: prevent crash when worker terminates after a file upload

---

build-static.sh
docs/fr/known-issues.md
docs/known-issues.md

fix(static): unbundle parallel extension

---

caddy/frankenphp/Caddyfile

Courtesy of @francislavoie, see https://github.com/dunglas/frankenphp/pull/832/files#r1629111111.

chore: simplify log config

---

docs/known-issues.md

Added documentation to provide troubleshooting assistance and solution for issues encountered with mailing and SSL/TLS.
Relates to issue: https://github.com/dunglas/frankenphp/issues/582

docs: Mail SSL/TLS issues documentation added to Known Issues

---

docker-bake.hcl

See https://github.com/golang/go/issues/68285, https://github.com/dunglas/frankenphp/discussions/899, https://github.com/dunglas/symfony-docker/issues/646.

fix: downgrade to Go 1.22.4 for Alpine builds

---

docs/config.md
docs/embed.md
docs/fr/config.md
docs/fr/embed.md

docs: customizing the configuration

---

build-static.sh

feat(static): add HTTP/2 support for ext-curl

---

docs/cn/compile.md
docs/tr/compile.md

docs: fix build/curl instructions in more languages

---

Dockerfile
alpine.Dockerfile
build-static.sh
caddy/br-skip.go
caddy/br.go
caddy/php-server.go
dev.Dockerfile
docs/compile.md

This will simplify compiling from sources.

feat: add build tag to skip Brotli support

---

CONTRIBUTING.md
README.md
docs/cn/CONTRIBUTING.md
docs/cn/laravel.md
docs/cn/worker.md
docs/fr/CONTRIBUTING.md
docs/fr/README.md
docs/fr/laravel.md
docs/fr/worker.md
docs/laravel.md
docs/tr/CONTRIBUTING.md
docs/tr/laravel.md
docs/tr/worker.md
docs/worker.md
install.sh

* The script is now available at https://frankenphp.dev/install.sh
* It now also supports Alpine Linux and similar (no `bash`, only `wget`)
* It uses emojis and `tput` to make the output nicer

feat: improve install script

---

frankenphp.c

Fix https://github.com/dunglas/frankenphp/pull/1058#issuecomment-2417472316.

fix: always include pthread.h

---

docs/fr/laravel.md
docs/laravel.md

See https://caddy.community/t/confused-about-access-logs/25992

docs(octane): explain how to get structured JSON logs

---

build-static.sh

https://github.com/dunglas/frankenphp/issues/791 is closed now.

feat(static): re-enable ext-parallel

---

Dockerfile
alpine.Dockerfile
docs/cn/docker.md
docs/fr/docker.md

Prevents an annoying warning in our CI (which is a false positive).

chore(docker): download mlocati/docker-php-extension-installer

---

frankenphp.go

Closes https://github.com/dunglas/frankenphp/issues/1020

fix: always ignore SIGPIPE

---

.github/workflows/docker.yaml
.github/workflows/static.yaml
alpine.Dockerfile

ci: don't compress using UPX for PRs

---

.github/workflows/docker.yaml
docs/cn/docker.md
docs/docker.md
docs/fr/docker.md
docs/tr/docker.md

We don't use this prefix anymore.

ci: remove remaining latest- prefix

---

docs/compile.md

docs: fix xcaddy instructions

---

testdata/benchmark.Caddyfile

As rightly suggested by @AlliBalliBaba

chore: simplify benchmark.Caddyfile

---

README.md
build-static.sh
docs/cn/README.md
docs/fr/README.md
docs/tr/README.md

Needs https://github.com/crazywhalecc/static-php-cli/issues/560 to be resolved

feat: build static binaries with 8.4

---

build-static.sh

Not necessary since https://github.com/crazywhalecc/static-php-cli/issues/560 and https://github.com/crazywhalecc/static-php-cli/issues/563.

chore: remove useless SPC workarounds

---

.github/workflows/docker.yaml

Fix issue introduced in #1255.

ci: fix artifact upload

---

build-static.sh
static-builder.Dockerfile

Better alternative to https://github.com/dunglas/frankenphp/pull/1257

feat(static): better libphp.a cache strategy

---

docs/cn/known-issues.md
docs/fr/known-issues.md
docs/known-issues.md
docs/tr/known-issues.md

Fibers support has been fixed in #1137.

docs: remove fibers from known issues

---

build-static.sh

fix(static): ARM Linux builds

---

docs/fr/performance.md
docs/performance.md

Closes https://github.com/dunglas/frankenphp/issues/940.

docs: add link for musl-related problems

---

CONTRIBUTING.md
dev.Dockerfile
internal/testserver/main.go

updating contibuting.md to make things work on the first try

update docs for first-time contributor

---

frankenphp.go

Compatibility with dynamic libphp on macOS: https://github.com/php/php-src/pull/17183

feat: compatibility with libphp.dylib on macOS

---

go.mod

update `go` and `toolchain` versions like `caddy/go.mod` https://github.com/dunglas/frankenphp/blob/16814581f9c481bd9ee58cf969ff59a74620ef81/caddy/go.mod#L3-L5

update go and toolchain version

---

.github/workflows/static.yaml

Fixes errors like that: https://github.com/dunglas/frankenphp/actions/runs/14617600988/job/41009356961
cc @DubbleClick, if you can double-check

ci: fix static GNU binary copy

---

frankenphp.go
internal/testserver/main.go
internal/watcher/watch_pattern.go
internal/watcher/watcher.go
phpmainthread.go
phpthread.go
scaling.go
threadworker.go

chore: add context to logs to make the linter happy

---

.github/workflows/static.yaml

Missing part of https://github.com/dunglas/frankenphp/pull/1534.

ci: fix GNU manifest

---

context.go
threadregular.go

Applies the fix from #1540 also to regular threads

fix: also fixes metrics with regular request timeouts

---

Dockerfile
alpine.Dockerfile
go.mod
static-builder-gnu.Dockerfile
static-builder-musl.Dockerfile

Removes the go toolchain patch version to fix the current Docker pipelines

fix: go toolchain versioning

---

caddy/php-server.go

Attempt to fix https://github.com/dunglas/frankenphp/issues/1414.
I didn't try yet.

fix: automatically change cwd when embedding an app

---

frankenphp.go

fix: linking on OpenBSD

---

internal/extgen/arginfo.go
internal/extgen/classparser.go
internal/extgen/funcparser.go
internal/extgen/gofile.go
internal/extgen/gofile_test.go
internal/extgen/nodes.go
internal/extgen/stub.go
internal/extgen/templates/extension.go.tpl
internal/extgen/validator.go
internal/extgen/validator_test.go

This was the last file not generated with Go templating mechanism

feat(gofile): use templates to generate the Go file

---

static-builder-musl.Dockerfile

closes https://github.com/php/frankenphp/issues/1787

fix https://github.com/php/frankenphp/issues/1787

---

docs/cn/CONTRIBUTING.md
docs/cn/README.md
docs/cn/classic.md
docs/cn/compile.md
docs/cn/config.md
docs/cn/docker.md
docs/cn/embed.md
docs/cn/extensions.md
docs/cn/known-issues.md
docs/cn/laravel.md
docs/cn/mercure.md
docs/cn/metrics.md
docs/cn/performance.md
docs/cn/production.md
docs/cn/static.md
docs/cn/worker.md
docs/cn/x-sendfile.md

FrankenPHP documentation has changed a lot since last year (cf https://github.com/php/frankenphp/issues/1763).
This commit updates the Chinese documentation to the latest English version.

docs: update Chinese documentation to latest version

---

docs/pt-br/CONTRIBUTING.md
docs/pt-br/README.md
docs/pt-br/classic.md
docs/pt-br/compile.md
docs/pt-br/config.md
docs/pt-br/docker.md
docs/pt-br/early-hints.md
docs/pt-br/embed.md
docs/pt-br/github-actions.md
docs/pt-br/known-issues.md
docs/pt-br/laravel.md
docs/pt-br/mercure.md
docs/pt-br/metrics.md
docs/pt-br/performance.md
docs/pt-br/production.md
docs/pt-br/static.md
docs/pt-br/worker.md
docs/pt-br/x-sendfile.md

- Translate file README.md
- Translate file CONTRIBUTING.md
- Translate file docs/classic.md
- Translate file docs/compile.md
- Translate file docs/config.md
- Translate file docs/docker.md
- Translate file docs/early-hints.md
- Translate file docs/embed.md
- Translate file docs/github-actions.md
- Translate file docs/known-issues.md
- Translate file docs/laravel.md
- Translate file docs/mercure.md
- Translate file docs/metrics.md
- Translate file docs/performance.md
- Translate file docs/production.md
- Translate file docs/static.md
- Translate file docs/worker.md
- Translate file docs/x-sendfile.md

feat: add Brazilian Portuguese translation

---

docs/compile.md
docs/config.md
docs/extensions.md

- Remove redundant sentence
- Remove unnecessary ~~ markup
- Add code formatting in frankenphp.* methods

fix: minor docs fixes

---

docs/cn/extensions.md
docs/extensions.md
docs/fr/extensions.md
docs/ja/extensions.md
docs/pt-br/extensions.md

Fix the docs to match https://github.com/php/frankenphp/blob/c564c3ffb9107fd7d28b583d073eaf224ac13caf/internal/extgen/arginfo.go#L16

fix: replace GEN_STUB_FILE by GEN_STUB_SCRIPT in the docs

---

types.go

Fix a type issue I introduced in #1877

fix: PHPValue() and GoValue() types
